-- MySQL Script generated by MySQL Workbench
-- Sat Dec  1 20:31:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyectoDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proyectoDB` ;

-- -----------------------------------------------------
-- Schema proyectoDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyectoDB` DEFAULT CHARACTER SET utf8 ;
USE `proyectoDB` ;

-- -----------------------------------------------------
-- Table `proyectoDB`.`Tipo_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectoDB`.`Tipo_user` (
  `id_Tipo` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_Tipo`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idTipo_user_UNIQUE` ON `proyectoDB`.`Tipo_user` (`id_Tipo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyectoDB`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectoDB`.`Usuario` (
  `id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Contraseña` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  `Apellido` VARCHAR(20) NOT NULL,
  `Nom_usuario` VARCHAR(20) NOT NULL,
  `Tipo_user` INT NOT NULL,
  PRIMARY KEY (`id_Usuario`),
  CONSTRAINT `tipo_user`
    FOREIGN KEY (`Tipo_user`)
    REFERENCES `proyectoDB`.`Tipo_user` (`id_Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idUsuario_UNIQUE` ON `proyectoDB`.`Usuario` (`id_Usuario` ASC) VISIBLE;

CREATE UNIQUE INDEX `Tipo_user_UNIQUE` ON `proyectoDB`.`Usuario` (`Tipo_user` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyectoDB`.`Tipo_Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectoDB`.`Tipo_Evento` (
  `id_Tipo` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_Tipo`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idTipo_user_UNIQUE` ON `proyectoDB`.`Tipo_Evento` (`id_Tipo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyectoDB`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectoDB`.`Evento` (
  `id_Evento` INT NOT NULL AUTO_INCREMENT,
  `Ubicacion` VARCHAR(45) NOT NULL,
  `Fecha` DATE NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  `Status` VARCHAR(20) NOT NULL,
  `Tipo_Evento` INT NOT NULL,
  `id_Usuario` INT NOT NULL,
  PRIMARY KEY (`id_Evento`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `proyectoDB`.`Usuario` (`id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT   ch_status CHECK ( Status IN ('Finalizado','Proximamente')),
  CONSTRAINT `id_tipo`
    FOREIGN KEY (`Tipo_Evento`)
    REFERENCES `proyectoDB`.`Tipo_Evento` (`id_Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idtable1_UNIQUE` ON `proyectoDB`.`Evento` (`id_Evento` ASC) VISIBLE;

CREATE INDEX `id_usuario_idx` ON `proyectoDB`.`Evento` (`id_Usuario` ASC) VISIBLE;

CREATE INDEX `id_tipo_idx` ON `proyectoDB`.`Evento` (`Tipo_Evento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyectoDB`.`Invitados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectoDB`.`Invitados` (
  `id_Invitados` INT NOT NULL AUTO_INCREMENT,
  `Cédula` VARCHAR(11) NOT NULL,
  `Apellido` VARCHAR(20) NOT NULL,
  `Sexo` VARCHAR(20) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  CONSTRAINT  ch_sexo CHECK ( Sexo IN ('M','F')),
  PRIMARY KEY (`id_Invitados`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_Invitado_UNIQUE` ON `proyectoDB`.`Invitados` (`id_Invitados` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyectoDB`.`Asisten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectoDB`.`Asisten` (
  `id_Evento` INT NOT NULL,
  `id_invitado` INT NOT NULL,
  `Status` BIT NOT NULL,
  PRIMARY KEY (`id_Evento`, `id_invitado`),
  CONSTRAINT `id_evento`
    FOREIGN KEY (`id_Evento`)
    REFERENCES `proyectoDB`.`Evento` (`id_Evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT  ch_Status_inv CHECK ( Status IN ('Presente','Ausente')),
  CONSTRAINT `id_invitado`
    FOREIGN KEY (`id_invitado`)
    REFERENCES `proyectoDB`.`Invitados` (`id_Invitados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_invitado_idx` ON `proyectoDB`.`Asisten` (`id_invitado` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
